name = "portal-os"
main = "src/index.ts"
compatibility_date = "2026-09-18"

account_id = "b96187fbfed864f60e67925517c2b9f2"
workers_dev = true

[vars]
PLANETARY_MODE = "production"
UMBRELLA_ENFORCEMENT = "enabled"

[[kv_namespaces]]
binding = "PLANETARY_MAX_SNAPSHOT"
id = "af7304e461a14ebd94f6a5fd2c7b7421"

[[d1_databases]]
binding = "PLANETARY_MAX_DB"
database_id = "6a0b0f4f-03f9-4d3e-b41b-c13310847686"
database_name = "planetary-max-db"
